/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import controlador.clsConexion;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;
import modelo.clsEstudiante;

/**
 *
 * @author 
 */
public class frmEstudiante extends javax.swing.JFrame {

    /**
     * Creates new form frmEstudiante
     */
    public frmEstudiante() {
        initComponents();
        objcon.conectar();
        valDoc.setVisible(false);
        valNom.setVisible(false);
        valApe.setVisible(false);
        valDir.setVisible(false);
        valTel.setVisible(false);
        bloqCampos();
    }
    
    clsConexion objcon = new clsConexion();
    clsEstudiante objEst = new clsEstudiante();
    
    public void capturar(){
    objEst.setDocEst(txtDocEst.getText());
    objEst.setNomEst(txtNomEst.getText());
    objEst.setApeEst(txtApeEst.getText());
    objEst.setDirEst(txtDirEst.getText());
    objEst.setTelEst(txtTelEst.getText());
    }
    
    int cont=0;
    public void validar() {
        if (txtDocEst.getText().isEmpty()) {txtDocEst.grabFocus();valDoc.setVisible(true);cont++;} 
            else{valDoc.setVisible(false);}
        if (txtNomEst.getText().isEmpty()) {txtNomEst.grabFocus();valNom.setVisible(true);cont++;} 
            else {valNom.setVisible(false);}
        if (txtApeEst.getText().isEmpty()) {txtApeEst.grabFocus();valApe.setVisible(true);cont++;} 
            else{valApe.setVisible(false);}
        if (txtDirEst.getText().isEmpty()) {txtDirEst.grabFocus();valDir.setVisible(true);cont++;} 
            else{valDir.setVisible(false);}
        if (txtTelEst.getText().length()==0) {txtTelEst.grabFocus();valTel.setVisible(true);cont++;}
            else{valTel.setVisible(false);}
    }
    
    public void guardar(){
        capturar();
        objEst.guardar();
    }

    public void buscar(){
        try {
            String bus = JOptionPane.showInputDialog("Digite el documento del estudiante");
            objEst.setDocEst(bus);
            objEst.buscar();
            if (objEst.datos.next()==true) {
                txtDocEst.setText(objEst.datos.getString(1));
                txtNomEst.setText(objEst.datos.getString(2));
                txtApeEst.setText(objEst.datos.getString(3));
                txtDirEst.setText(objEst.datos.getString(4));
                txtTelEst.setText(objEst.datos.getString(5));
                btnGuardar.setEnabled(false);
                btnModificar.setEnabled(true);
            } else {
                JOptionPane.showMessageDialog(null, "El estudiante no existe");
                limpiar();
                bloqCampos();
            }
            
        } catch (Exception e) {
            limpiar();
            bloqCampos();
        }
        
    }
    
    public void actualizar(){
        capturar();
        objEst.actualizar();
    }
    
    public void bloqCampos(){
        txtDocEst.setEnabled(false);
        txtNomEst.setEnabled(false);
        txtApeEst.setEnabled(false);
        txtDirEst.setEnabled(false);
        txtTelEst.setEnabled(false);
        btnNuevo.setEnabled(true);
        btnGuardar.setEnabled(false);
        btnBuscar.setEnabled(true);
        btnModificar.setEnabled(false);
        btnActualizar.setEnabled(false);
    }
    
    public void desBloqCampos(){
        txtDocEst.setEnabled(true);
        txtNomEst.setEnabled(true);
        txtApeEst.setEnabled(true);
        txtDirEst.setEnabled(true);
        txtTelEst.setEnabled(true);
        btnNuevo.setEnabled(true);
        btnGuardar.setEnabled(true);
        btnBuscar.setEnabled(true);
        btnModificar.setEnabled(false);
        btnActualizar.setEnabled(false);
    }
    
    public void limpiar(){
        txtDocEst.setText(null);
        txtNomEst.setText(null);
        txtApeEst.setText(null);
        txtDirEst.setText(null);
        txtTelEst.setText(null);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnEliminar = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        txtDocEst = new javax.swing.JTextField();
        txtNomEst = new javax.swing.JTextField();
        txtApeEst = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtDirEst = new javax.swing.JTextField();
        txtTelEst = new javax.swing.JTextField();
        btnNuevo = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        btnBuscar = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        btnActualizar = new javax.swing.JButton();
        btnRegresar = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        valDoc = new javax.swing.JLabel();
        valNom = new javax.swing.JLabel();
        valApe = new javax.swing.JLabel();
        valDir = new javax.swing.JLabel();
        valTel = new javax.swing.JLabel();

        btnEliminar.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Estudiante");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 470, 10));

        txtDocEst.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtDocEst.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtDocEstKeyPressed(evt);
            }
        });
        getContentPane().add(txtDocEst, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 50, 280, 30));

        txtNomEst.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        getContentPane().add(txtNomEst, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 90, 280, 30));

        txtApeEst.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        getContentPane().add(txtApeEst, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 130, 280, 30));

        jLabel1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel1.setText("Documento");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, -1, -1));

        jLabel2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel2.setText("Nombre");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, -1, -1));

        jLabel3.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel3.setText("Apellido");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, -1, -1));

        jLabel4.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel4.setText("Direccion");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, -1, -1));

        jLabel5.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel5.setText("Telefono");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, -1, -1));

        txtDirEst.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        getContentPane().add(txtDirEst, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 170, 280, 30));

        txtTelEst.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtTelEst.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtTelEstKeyPressed(evt);
            }
        });
        getContentPane().add(txtTelEst, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 210, 280, 30));

        btnNuevo.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnNuevo.setText("Nuevo");
        btnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoActionPerformed(evt);
            }
        });
        getContentPane().add(btnNuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, 80, 30));

        btnGuardar.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        getContentPane().add(btnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 260, 90, 30));

        btnBuscar.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });
        getContentPane().add(btnBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 260, 80, 30));

        btnModificar.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnModificar.setText("Modificar");
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });
        getContentPane().add(btnModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 260, 90, 30));

        btnActualizar.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnActualizar.setText("Actualizar");
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });
        getContentPane().add(btnActualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 260, 100, 30));

        btnRegresar.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnRegresar.setText("Regresar");
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });
        getContentPane().add(btnRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 0, -1, 30));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel6.setText("Estudiante");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 0, 120, 30));

        valDoc.setForeground(new java.awt.Color(204, 0, 0));
        valDoc.setText("Obligatorio");
        getContentPane().add(valDoc, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 50, 80, 30));

        valNom.setForeground(new java.awt.Color(204, 0, 0));
        valNom.setText("Obligatorio");
        getContentPane().add(valNom, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 90, 80, 30));

        valApe.setForeground(new java.awt.Color(204, 0, 0));
        valApe.setText("Obligatorio");
        getContentPane().add(valApe, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 130, 80, 30));

        valDir.setForeground(new java.awt.Color(204, 0, 0));
        valDir.setText("Obligatorio");
        getContentPane().add(valDir, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 170, 80, 30));

        valTel.setForeground(new java.awt.Color(204, 0, 0));
        valTel.setText("Obligatorio");
        getContentPane().add(valTel, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 210, 80, 30));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
cont=0;
validar();
if(cont==0){
        guardar();
        limpiar();
        bloqCampos();
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
this.buscar();        // TODO add your handling code here:
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
       // TODO add your handling code here:
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
cont=0;
validar();
if(cont==0){
    actualizar();
    limpiar();
    bloqCampos();
}
        // TODO add your handling code here:
    }//GEN-LAST:event_btnActualizarActionPerformed

    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed
desBloqCampos();
limpiar();
        // TODO add your handling code here:
    }//GEN-LAST:event_btnNuevoActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        txtDocEst.setEnabled(false);
        txtNomEst.setEnabled(true);
        txtApeEst.setEnabled(true);
        txtDirEst.setEnabled(true);
        txtTelEst.setEnabled(true);
        btnNuevo.setEnabled(true);
        btnGuardar.setEnabled(false);
        btnBuscar.setEnabled(true);
        btnModificar.setEnabled(false);
        btnActualizar.setEnabled(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_btnModificarActionPerformed

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
frmIndex objIndex = new frmIndex();
objIndex.setVisible(true);
this.setVisible(false);
// TODO add your handling code here:
    }//GEN-LAST:event_btnRegresarActionPerformed

    private void txtDocEstKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDocEstKeyPressed
txtDocEst.addKeyListener(new KeyAdapter() {

public void keyTyped(KeyEvent e) {
     char c = e.getKeyChar();
if (!((Character.isDigit(c) || (c == KeyEvent.VK_BACK_SPACE) || (c ==  KeyEvent.VK_DELETE)))) {
                getToolkit().beep();
                e.consume();
            }
        }
    });        
// TODO add your handling code here:
    }//GEN-LAST:event_txtDocEstKeyPressed

    private void txtTelEstKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTelEstKeyPressed
txtTelEst.addKeyListener(new KeyAdapter() {

public void keyTyped(KeyEvent e) {
     char c = e.getKeyChar();
if (!((Character.isDigit(c) || (c == KeyEvent.VK_BACK_SPACE) || (c ==  KeyEvent.VK_DELETE)))) {
                getToolkit().beep();
                e.consume();
            }
        }
    });
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTelEstKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmEstudiante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmEstudiante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmEstudiante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmEstudiante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmEstudiante().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JButton btnNuevo;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField txtApeEst;
    private javax.swing.JTextField txtDirEst;
    private javax.swing.JTextField txtDocEst;
    private javax.swing.JTextField txtNomEst;
    private javax.swing.JTextField txtTelEst;
    private javax.swing.JLabel valApe;
    private javax.swing.JLabel valDir;
    private javax.swing.JLabel valDoc;
    private javax.swing.JLabel valNom;
    private javax.swing.JLabel valTel;
    // End of variables declaration//GEN-END:variables
}
