/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import javax.swing.JOptionPane;
import modelo.clsMateria;

/**
 *
 * @author 
 */
public class frmMateria extends javax.swing.JFrame {

    /**
     * Creates new form frmMateria
     */
    public frmMateria() {
        initComponents();
        valNom.setVisible(false);
        valGra.setVisible(false);
        txtCodMat.setEnabled(false);
        bloqCampos();
    }

    clsMateria objMat = new clsMateria();
    
    public void capturar(){
        objMat.setNomMat(txtNomMat.getText());
        objMat.setGraMat(cbxGraMat.getSelectedItem().toString());
    }
    
    int cont=0;
    public void validar() {
        if (txtNomMat.getText().isEmpty()) {txtNomMat.grabFocus();valNom.setVisible(true); cont++;}
            else{valNom.setVisible(false);}
        if (cbxGraMat.getSelectedItem()=="Seleccione") {cbxGraMat.grabFocus();valGra.setVisible(true);cont++;}
            else{valGra.setVisible(false);}
    }
    
    public void nuevo(){
        try {
            objMat.contar();
            while (objMat.contCod.next()==true) {                
                txtCodMat.setText(""+objMat.contCod.getInt(1)); 
            }
        } catch (Exception e) {
        }  
    }
    
    public void guardar(){
        cont=0;
        validar();
        if (cont==0) {
            capturar();
            objMat.guardar();
            limpiar();
            bloqCampos();
        }
    }
    
    public void buscar(){
        try {
            String bus = JOptionPane.showInputDialog("Digite el codigo de la materia");
            objMat.setCodMat(Integer.parseInt(bus));
            objMat.buscar();
            if (objMat.datos.next()==true) {
                txtCodMat.setText(objMat.datos.getString(1));
                txtNomMat.setText(objMat.datos.getString(2));
                cbxGraMat.setSelectedItem(objMat.datos.getString(3));
                txtNomMat.setEnabled(false);
                cbxGraMat.setEnabled(false);
                btnGuardar.setEnabled(false);
                btnModificar.setEnabled(true);
            } else {
                JOptionPane.showMessageDialog(null, "La materia no existe");
                    limpiar();
                    bloqCampos();
            }
        } catch (Exception e) {
                limpiar();
                bloqCampos();
        }   
    }
    
    public void actualizar(){
        cont=0;
        validar();
        if (cont==0) {
            capturar();
            objMat.actualizar();
            limpiar();
            bloqCampos();
        }
    }
    
    public void bloqCampos(){
        txtCodMat.setEnabled(false);
        txtNomMat.setEnabled(false);
        cbxGraMat.setEnabled(false);
        btnNuevo.setEnabled(true);
        btnGuardar.setEnabled(false);
        btnBuscar.setEnabled(true);
        btnModificar.setEnabled(false);
        btnActualizar.setEnabled(false);
    }
    
    public void desBloqCampos(){
        txtNomMat.setEnabled(true);
        cbxGraMat.setEnabled(true);
        btnNuevo.setEnabled(true);
        btnGuardar.setEnabled(true);
        btnBuscar.setEnabled(true);
        btnModificar.setEnabled(false);
        btnActualizar.setEnabled(false);
    }
    
    public void limpiar(){
        txtCodMat.setText(null);
        txtNomMat.setText(null);
        cbxGraMat.setSelectedIndex(0);
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnEliminar = new javax.swing.JButton();
        txtCodMat = new javax.swing.JTextField();
        txtNomMat = new javax.swing.JTextField();
        cbxGraMat = new javax.swing.JComboBox<>();
        btnGuardar = new javax.swing.JButton();
        btnBuscar = new javax.swing.JButton();
        btnActualizar = new javax.swing.JButton();
        btnRegresar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        Materias = new javax.swing.JLabel();
        btnModificar = new javax.swing.JButton();
        btnNuevo = new javax.swing.JButton();
        valNom = new javax.swing.JLabel();
        valGra = new javax.swing.JLabel();

        btnEliminar.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnEliminar.setText("Eliminar");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtCodMat.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtCodMat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCodMatActionPerformed(evt);
            }
        });
        getContentPane().add(txtCodMat, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 70, 140, 30));

        txtNomMat.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        getContentPane().add(txtNomMat, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 120, 140, 30));

        cbxGraMat.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        cbxGraMat.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione", "Primero", "Segundo", "Tercero", "Cuarto", "Quinto" }));
        getContentPane().add(cbxGraMat, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 170, 140, 30));

        btnGuardar.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        getContentPane().add(btnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 240, 90, 30));

        btnBuscar.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });
        getContentPane().add(btnBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 240, 90, 30));

        btnActualizar.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnActualizar.setText("Actualizar");
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });
        getContentPane().add(btnActualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 240, -1, 30));

        btnRegresar.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnRegresar.setText("Regresar");
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });
        getContentPane().add(btnRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 0, -1, 30));

        jLabel1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel1.setText("Codigo");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 70, 80, 30));

        jLabel2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel2.setText("Nombre");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 120, 60, 30));

        jLabel3.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel3.setText("Grado");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 170, 60, 30));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 480, 20));

        Materias.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        Materias.setText("Materias");
        getContentPane().add(Materias, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 0, 90, 30));

        btnModificar.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnModificar.setText("Modificar");
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });
        getContentPane().add(btnModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 240, 100, 30));

        btnNuevo.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnNuevo.setText("Nuevo");
        btnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoActionPerformed(evt);
            }
        });
        getContentPane().add(btnNuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(13, 240, 80, 30));

        valNom.setForeground(new java.awt.Color(153, 0, 0));
        valNom.setText("Obligatorio");
        getContentPane().add(valNom, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 120, 70, 30));

        valGra.setForeground(new java.awt.Color(153, 0, 0));
        valGra.setText("Obligatorio");
        getContentPane().add(valGra, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 170, 80, 30));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtCodMatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodMatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCodMatActionPerformed

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
frmIndex objIndex = new frmIndex();
objIndex.setVisible(true);
this.setVisible(false);
// TODO add your handling code here:
    }//GEN-LAST:event_btnRegresarActionPerformed

    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed
limpiar();
nuevo();
desBloqCampos();
// TODO add your handling code here:
    }//GEN-LAST:event_btnNuevoActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
guardar();
// TODO add your handling code here:
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
buscar();
// TODO add your handling code here:
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        txtCodMat.setEnabled(false);
        txtNomMat.setEnabled(true);
        cbxGraMat.setEnabled(true);
        btnNuevo.setEnabled(true);
        btnGuardar.setEnabled(false);
        btnBuscar.setEnabled(true);
        btnModificar.setEnabled(false);
        btnActualizar.setEnabled(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_btnModificarActionPerformed

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
actualizar();
// TODO add your handling code here:
    }//GEN-LAST:event_btnActualizarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmMateria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmMateria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmMateria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmMateria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmMateria().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Materias;
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JButton btnNuevo;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JComboBox<String> cbxGraMat;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField txtCodMat;
    private javax.swing.JTextField txtNomMat;
    private javax.swing.JLabel valGra;
    private javax.swing.JLabel valNom;
    // End of variables declaration//GEN-END:variables
}
